import { Button, IconButton, TextField, Typography } from '@mui/material'
import axios, { AxiosResponse } from 'axios'
import getOAIResponse, { estimateCost } from '../lib/oai-util'
import { useEffect, useState } from 'react'

import ContentCopyIcon from '@mui/icons-material/ContentCopy';
import { Data } from './api/oai'
import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [input, setInput] = useState('')
  const [output, setOutput] = useState('')
  const [cost, setCost] = useState('')

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setInput(e.target.value)
  }

  const useOAI = async () => {
    try {
      const { data } = await axios.post<Data>('/api/oai', {
        params: {
          prompt: input
        }
      })
      setOutput(data.edited)
    } catch (err: any) {
      alert('Error: ' + err)
    }
  }

  useEffect(() => {
    estimateCost(input).then(setCost);
  }, [input]);
  
  return (
    <>
      <Head>
        <title>Email Editor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Typography variant="h3" className="max-h-[15vh]">Email Editor</Typography>
        <div className="min-w-screen min-h-[80vh] flex flex-col justify-center items-center">
          <div className='flex flex-row'>
            <TextField 
              id="outlined-basic" 
              label="Input" 
              variant="outlined" 
              className="max-w-[30vw] min-h-[60vh] min-w-[20vw]" 
              multiline 
              rows={20}
              value={input} 
              onChange={handleChange}
            />
            <TextField 
              disabled 
              id="outlined-basic" 
              label="Output" 
              variant="outlined" 
              className="max-w-[30vw] min-h-[60vh] min-w-[20vw]" 
              multiline 
              rows={20}
              value={output}
            />
            <IconButton
              className="position relative top-[-30vh] right-10 hover:bg-none"
              onClick={() => {
                navigator.clipboard.writeText(output);
              }}
            >
              <ContentCopyIcon />
            </IconButton>
            {/* add a copy button using an icon placed inside the Output textfield in the top right */}
            

          </div>
          <div className='flex flex-row justify-between items-center min-w-[40vw]'>
            <Button onClick={useOAI}>Edit</Button>
            <Typography variant="body1">Estimated Cost: {cost}</Typography>
          </div>
        </div>
      </main>
    </>
  )
}
