import { Button, TextField, Typography } from '@mui/material'
import getOAIResponse, { estimateCost } from '../lib/oai'
import { useEffect, useState } from 'react'

import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [input, setInput] = useState('')
  const [output, setOutput] = useState('')
  const [cost, setCost] = useState('')

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setInput(e.target.value)
  }

  const handleClick = async () => {
    try {
      const data = await getOAIResponse(input)
      setOutput(data)
    } catch (error) {
      console.log(error)
      alert('Error!')
    }
    
  }

  useEffect(() => {
    estimateCost(input).then(setCost);
  }, [input]);
  
  return (
    <>
      <Head>
        <title>Email Editor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Typography variant="h1">Email Editor</Typography>
        <div className={styles.inputs}>
          <div>
            <TextField 
              id="outlined-basic" 
              label="Input" 
              variant="outlined" 
              className={styles.input} 
              multiline 
              value={input} 
              onChange={handleChange}
            />
            <Button onClick={handleClick}>Edit</Button>
          </div>
          <div>
            <TextField 
              disabled 
              id="outlined-basic" 
              label="Output" 
              variant="outlined" 
              className={styles.input} 
              multiline 
              value={output}
            />
            <Typography variant="h6">Estimated Cost: {cost}</Typography>
          </div>
        </div>
      </main>
    </>
  )
}
